# Generated by Django 3.1.4 on 2020-12-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shepherd', '0006_auto_20201209_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click link above to read blog post...', max_length=255),
        ),
    ]
